### ISSUE TITLE
double free or corruption (!prev)

### ISSUE THREAD

**Issue by Fl4shy** [fireeye/gocat#5]
double free or corruption (!prev)
SIGABRT: abort
PC=0x7f3ec49d5ce1 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4b80f2, 0xc0000d6480, 0x0)
        /usr/lib/go-1.15/src/runtime/cgocall.go:133 +0x5b fp=0xc0000d6450 sp=0xc0000d6418 pc=0x40585b
github.com/fireeye/gocat._Cfunc_free(0x7cc0680)
        _cgo_gotypes.go:1776 +0x45 fp=0xc0000d6480 sp=0xc0000d6450 pc=0x4ad465
github.com/fireeye/gocat.(*Hashcat).GetStatus.func1.1()
        /usr/lib/go-1.15/src/github.com/fireeye/gocat/gocat_status.go:49 +0x53 fp=0xc0000d64b8 sp=0xc0000d6480 pc=0x4b2cb3
runtime.call32(0x0, 0xc0000982d0, 0x0, 0x0)
        /usr/lib/go-1.15/src/runtime/asm_amd64.s:540 +0x3e fp=0xc0000d64e8 sp=0xc0000d64b8 pc=0x46515e
runtime.reflectcallSave(0xc0000d6628, 0xc0000982d0, 0x0, 0xc000000000)
        /usr/lib/go-1.15/src/runtime/panic.go:881 +0x58 fp=0xc0000d6518 sp=0xc0000d64e8 pc=0x434eb8
runtime.runOpenDeferFrame(0xc000000180, 0xc0000ba050, 0xc0000d6670)
        /usr/lib/go-1.15/src/runtime/panic.go:855 +0x2cd fp=0xc0000d65a8 sp=0xc0000d6518 pc=0x434d6d
panic(0x4d4280, 0x589a70)
        /usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9 fp=0xc0000d6670 sp=0xc0000d65a8 pc=0x435139
runtime.panicmem(...)
        /usr/lib/go-1.15/src/runtime/panic.go:212
runtime.sigpanic()
        /usr/lib/go-1.15/src/runtime/signal_unix.go:742 +0x413 fp=0xc0000d66a0 sp=0xc0000d6670 pc=0x4498d3
indexbytebody(0x5, 0xffb, 0xc0000a8000, 0xc0000d66f0, 0xffb, 0x0, 0x5, 0x5, 0xffb, 0xc0000d6748, ...)
        /usr/lib/go-1.15/src/internal/bytealg/indexbyte_amd64.s:48 +0x2c fp=0xc0000d66a8 sp=0xc0000d66a0 pc=0x403e0c
runtime.findnull(0x5, 0x7cc0650)
        /usr/lib/go-1.15/src/runtime/string.go:454 +0x87 fp=0xc0000d6700 sp=0xc0000d66a8 pc=0x44fa87
runtime.gostring(0x5, 0xc0000b4020, 0x20)
        /usr/lib/go-1.15/src/runtime/string.go:320 +0x2f fp=0xc0000d6758 sp=0xc0000d6700 pc=0x463c2f
github.com/fireeye/gocat._Cfunc_GoString(...)
        _cgo_gotypes.go:1756
github.com/fireeye/gocat.(*Hashcat).GetStatus(0xc0000bc000, 0x0)
        /usr/lib/go-1.15/src/github.com/fireeye/gocat/gocat_status.go:61 +0x1ab fp=0xc0000d69d8 sp=0xc0000d6758 pc=0x4b016b
github.com/fireeye/gocat.callback(0xb0, 0xc0000bc000, 0xc0000bc000, 0x0, 0x0)
        /usr/lib/go-1.15/src/github.com/fireeye/gocat/gocat.go:288 +0xb1b fp=0xc0000d6e90 sp=0xc0000d69d8 pc=0x4af8bb
github.com/fireeye/gocat._cgoexpwrap_9a0ee33eb240_callback(0xb0, 0xc0000bc000, 0xc0000bc000, 0x0, 0x0)
        _cgo_gotypes.go:2012 +0x51 fp=0xc0000d6ec8 sp=0xc0000d6e90 pc=0x4addd1
runtime.call64(0x0, 0x7ffe5f460dc0, 0x7ffe5f460e80, 0x28)
        /usr/lib/go-1.15/src/runtime/asm_amd64.s:541 +0x3e fp=0xc0000d6f18 sp=0xc0000d6ec8 pc=0x4651fe
runtime.cgocallbackg1(0x0)
        /usr/lib/go-1.15/src/runtime/cgocall.go:332 +0x1a5 fp=0xc0000d6fb0 sp=0xc0000d6f18 pc=0x405c25
runtime.cgocallbackg(0x0)
        /usr/lib/go-1.15/src/runtime/cgocall.go:207 +0xc5 fp=0xc0000d7018 sp=0xc0000d6fb0 pc=0x4059c5
runtime.cgocallback_gofunc(0x40587f, 0x4b82a2, 0xc0000d70a8, 0xc0000c3098)
        /usr/lib/go-1.15/src/runtime/asm_amd64.s:794 +0x9b fp=0xc0000d7038 sp=0xc0000d7018 pc=0x4668db
runtime.asmcgocall(0x4b82a2, 0xc0000d70a8)
        /usr/lib/go-1.15/src/runtime/asm_amd64.s:641 +0x42 fp=0xc0000d7040 sp=0xc0000d7038 pc=0x466762
runtime.cgocall(0x4b82a2, 0xc0000d70a8, 0xc0000bc000)
        /usr/lib/go-1.15/src/runtime/cgocall.go:143 +0x7f fp=0xc0000d7078 sp=0xc0000d7040 pc=0x40587f
github.com/fireeye/gocat._Cfunc_hashcat_session_execute(0xc0000bc000, 0xc000000000)
        _cgo_gotypes.go:1883 +0x49 fp=0xc0000d70a8 sp=0xc0000d7078 pc=0x4ad8c9
github.com/fireeye/gocat.(*Hashcat).RunJob.func7(0xc0000bc000, 0xc0000a8060)
        /usr/lib/go-1.15/src/github.com/fireeye/gocat/gocat.go:168 +0x5f fp=0xc0000d70d8 sp=0xc0000d70a8 pc=0x4b29bf
github.com/fireeye/gocat.(*Hashcat).RunJob(0xc0000bc000, 0xc0000cc000, 0x6, 0x8, 0x0, 0x0)
        /usr/lib/go-1.15/src/github.com/fireeye/gocat/gocat.go:168 +0x2ef fp=0xc0000d77a0 sp=0xc0000d70d8 pc=0x4ae6af
github.com/fireeye/gocat.(*Hashcat).RunJobWithOptions(0xc0000bc000, 0xc0000b2018, 0xc0000b2010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.15/src/github.com/fireeye/gocat/gocat.go:188 +0xd2 fp=0xc0000d7a40 sp=0xc0000d77a0 pc=0x4aebf2
main.main()
        /root/go/src/test/hctest.go:65 +0x265 fp=0xc0000d7f88 sp=0xc0000d7a40 pc=0x4b7805
runtime.main()
        /usr/lib/go-1.15/src/runtime/proc.go:204 +0x209 fp=0xc0000d7fe0 sp=0xc0000d7f88 pc=0x4380c9
runtime.goexit()
        /usr/lib/go-1.15/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000d7fe8 sp=0xc0000d7fe0 pc=0x466b81

**Comment by kulinacs** [comment]
Please attempt to recompile libhashcat with `BRAIN_ENABLE` set to 0.
